ctf docker: add extra packages
libc6-dev and libc-dev-bin fix:

    libc6-dev : Depends: libc6 (= 2.31-13+deb11u5) but 2.31-13+deb11u4 is to be installed

procps fixes gef:

    FileNotFoundError: Missing file `ps`

less, lsb_release and sudo are small and useful.